/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MonHocDAO;
import Model.MonHoc;
import Util.SQLConnection;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duc
 */
public class Cu_MonHoc extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
 DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new customizer Cu_MonHoc
     */
    public Cu_MonHoc() {
       initComponents();
        
        loadDuLieuLenLuoi();
        btnXoa.setEnabled(false);
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    public void reset() {
        txtHeSo_GiuaKy.setText("");
        txtTinChi.setText("");
        txtHeSo_CuoiKy.setText("");
        txtTenMonHoc.setText("");
        //  txtTenSinhVien.setText("");
        txtMaMonHoc.setText("");
        txtTimKiem.setText("");
        btnThem.setEnabled(true);
        btnXoa.setEnabled(false);
        txtMaMonHoc.setEnabled(true);

    }
    private void loadDuLieuLenLuoi() {
        dtm = new DefaultTableModel();
        //dtm.addColumn("Tên Sinh Viên");

        dtm.addColumn("Mã Môn Học");
        dtm.addColumn("Tên Môn Học");
        dtm.addColumn("Tín Chỉ");
        dtm.addColumn("Hệ Số Giữa Kỳ");
        dtm.addColumn("Hệ Số Cuối Kỳ");

        MonHocDAO monHocDAO = new MonHocDAO();
        List<MonHoc> monHocList = monHocDAO.selectAll();
        for (MonHoc monHoc : monHocList) {
            Vector vt = new Vector();
            vt.add(monHoc.getMaMonHoc());
            vt.add(monHoc.getTenMonHoc());
            vt.add(monHoc.getTinChi());
            vt.add(monHoc.getHeSoGiuaKy());
            vt.add(monHoc.getHeSoCuoiKy());
            dtm.addRow(vt);
        }
        tbl_MonHoc.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtMaMonHoc = new javax.swing.JTextField();
        txtTenMonHoc = new javax.swing.JTextField();
        txtTinChi = new javax.swing.JTextField();
        txtHeSo_GiuaKy = new javax.swing.JTextField();
        txtHeSo_CuoiKy = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_MonHoc = new javax.swing.JTable();

        jPanel3.setBackground(new java.awt.Color(255, 13, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 13, 255), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Mã Môn Học");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Tên Môn Học");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Tín Chỉ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Hệ Số Giữa Kỳ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Hệ Số Cuối Kỳ");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 13, 255)));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ADD.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        btnReset.setText("Xóa Trắng");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhat)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 13, 255)), "TÌM KIẾM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search-icon.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTimKiem)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHeSo_CuoiKy, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeSo_GiuaKy, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeSo_GiuaKy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeSo_CuoiKy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("     MÔN HỌC          ", jPanel1);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 13, 255), 2));

        tbl_MonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_MonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_MonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_MonHoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            if (txtMaMonHoc.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Mã Môn Học");
            } else if (txtTenMonHoc.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Tên Môn Học");
            } else if (txtTinChi.getText().isEmpty() && txtTinChi.getText() != null) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Số Tín Chỉ");
            } else if (txtHeSo_GiuaKy.getText().isEmpty() && txtHeSo_GiuaKy.getText() != null) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Hệ Số Giữa Kỳ");
            } else if (txtHeSo_CuoiKy.getText().isEmpty() && txtHeSo_CuoiKy.getText() != null) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Hệ Số Cuối Kỳ");
            }
            MonHocDAO monHocD = new MonHocDAO();
            MonHoc monHoc = new MonHoc(txtMaMonHoc.getText(), txtTenMonHoc.getText(), Integer.parseInt(txtTinChi.getText()), Float.parseFloat(txtHeSo_GiuaKy.getText()), Float.parseFloat(txtHeSo_CuoiKy.getText()));
            boolean result = monHocD.insert(monHoc);
            boolean checkMH = SQLConnection.Kiem_Tra_Trung("tbl_MONHOC", "MA_MON_HOC", txtMaMonHoc.getText());
            if (result == false) {
                if (checkMH == true) {
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thành Công !");
                } else if (checkMH == false) {
                    JOptionPane.showMessageDialog(this, "Mã Môn Học Đã Tồn Tại, Bạn Vui Lòng Nhập Lại ! ");
                }
            }
            reset();
            loadDuLieuLenLuoi();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xóa Không ", "Thông Báo", OK_CANCEL_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            int row = tbl_MonHoc.getSelectedRow();
            String maMonHoc = (String) tbl_MonHoc.getValueAt(row, 0);
            MonHocDAO monHocD = new MonHocDAO();
            MonHoc monHoc = new MonHoc(maMonHoc);
            boolean result = monHocD.delete(monHoc);
            if (result == false) {
                JOptionPane.showMessageDialog(this, "Xóa Thành Công !");
            }
            reset();
            loadDuLieuLenLuoi();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if (txtTenMonHoc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Tên Môn Học");
        } else if (txtTinChi.getText().isEmpty() && txtTinChi.getText() != null) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Số Tín Chỉ");
        } else if (txtHeSo_GiuaKy.getText().isEmpty() && txtHeSo_GiuaKy.getText() != null) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Hệ Số Giữa Kỳ");
        } else if (txtHeSo_CuoiKy.getText().isEmpty() && txtHeSo_CuoiKy.getText() != null) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Hệ Số Cuối Kỳ");
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Cập Nhật Không ", "Thông Báo", OK_CANCEL_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            MonHoc mh = new MonHoc(txtTenMonHoc.getText(), Integer.parseInt(txtTinChi.getText()), Float.parseFloat(txtHeSo_GiuaKy.getText()), Float.parseFloat(txtHeSo_CuoiKy.getText()));
            mh.setMaMonHoc(txtMaMonHoc.getText());
            MonHocDAO mhD = new MonHocDAO();
            boolean result = mhD.update(mh);
            if (result == false) {
                JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công!");
            }
            reset();
            loadDuLieuLenLuoi();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        //        dtm = new DefaultTableModel();
        //        dtm.addColumn("Mã Sinh Viên");
        //        dtm.addColumn("Mã Môn Học");
        //        dtm.addColumn("Điểm Giữa Kỳ");
        //        dtm.addColumn("Điểm Cuối Kỳ");
        //        dtm.addColumn("Điểm Tổng Kết");
        //
        //        MonHocDAO monHocDAO = new MonHocDAO();
        //
        //
        // MonHoc d = new MonHoc(txtMaSinhVien.getText(), txtMaMonHoc.getText(),  d.setMonHocGiuaKy(Float.parseFloat(txtMonHocGiuaKy.getText())),d.setMonHocCuoiKy(Float.parseFloat(txtMonHocCuoiKy.getText())),d.setMonHocTongKet(Float.parseFloat(txtMonHocTongKet.getText())));

        //     List<MonHoc> monHocList = monHocDAO.search(d);
        //        for (MonHoc monHoc : monHocList) {
            //            Vector vt = new Vector();
            //            vt.add(monHoc.getMaSinhVien());
            //            vt.add(monHoc.getMaMonHoc());
            //            vt.add(monHoc.getMonHocGiuaKy());
            //            vt.add(monHoc.getMonHocCuoiKy());
            //            vt.add(monHoc.getMonHocTongKet());
            //            dtm.addRow(vt);
            //        }
        //        tbl_MonHoc.setModel(dtm);
        MonHocDAO monHocD = new MonHocDAO();
        String input = txtTimKiem.getText();
        // monHocD.search1(input);
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String input = txtTimKiem.getText();
        dtm = new DefaultTableModel();
        dtm.addColumn("Mã Môn Học");
        dtm.addColumn("Tên Môn Học");
        dtm.addColumn("Tín Chỉ");
        dtm.addColumn("Hệ Số Giữa Kỳ");
        dtm.addColumn("Hệ Số Cuối Kỳ");
        MonHocDAO monHocDAO = new MonHocDAO();
        //MonHoc mh = new MonHoc();
        // MonHoc mh = new MonHoc(txtTenMonHoc.getText(), Integer.parseInt(txtTinChi.getText()), Float.parseFloat(txtHeSo_GiuaKy.getText()), Float.parseFloat(txtHeSo_CuoiKy.getText()));
        //MonHoc mh = new MonHoc(txtMaMonHoc.getText(), txtTenMonHoc.getText(), Integer.parseInt(txtTinChi.getText()), Float.parseFloat(txtHeSo_GiuaKy.getText()), Float.parseFloat(txtHeSo_CuoiKy.getText()));

        //MonHoc input = new MonHoc(txtMaMonHoc.getText(), txtTenMonHoc.getText(), Integer.parseInt(txtTinChi.getText()));
        List<MonHoc> monHocList = monHocDAO.search1(input);

        for (MonHoc monHoc : monHocList) {
            Vector vt = new Vector();
            vt.add(monHoc.getMaMonHoc());
            vt.add(monHoc.getTenMonHoc());
            vt.add(monHoc.getTinChi());
            vt.add(monHoc.getHeSoGiuaKy());
            vt.add(monHoc.getHeSoCuoiKy());
            dtm.addRow(vt);
        }
        tbl_MonHoc.setModel(dtm);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tbl_MonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_MonHocMouseClicked
        int row = tbl_MonHoc.getSelectedRow();
        String maMonHoc = (String) tbl_MonHoc.getValueAt(row, 0);
        String tenMonHoc = (String) tbl_MonHoc.getValueAt(row, 1);
        Integer tinChi = (Integer) tbl_MonHoc.getValueAt(row, 2);
        Float heSoGiuaKy = (Float) tbl_MonHoc.getValueAt(row, 3);
        Float heSoCuoiKy = (Float) tbl_MonHoc.getValueAt(row, 4);

        txtMaMonHoc.setText(maMonHoc);
        txtTenMonHoc.setText(tenMonHoc);
        txtTinChi.setText(tinChi.toString());
        txtHeSo_GiuaKy.setText(heSoGiuaKy.toString());
        txtHeSo_CuoiKy.setText(heSoCuoiKy.toString());
        btnThem.setEnabled(false);
        btnXoa.setEnabled(true);
        txtMaMonHoc.setEnabled(false);
    }//GEN-LAST:event_tbl_MonHocMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_MonHoc;
    private javax.swing.JTextField txtHeSo_CuoiKy;
    private javax.swing.JTextField txtHeSo_GiuaKy;
    private javax.swing.JTextField txtMaMonHoc;
    private javax.swing.JTextField txtTenMonHoc;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTinChi;
    // End of variables declaration//GEN-END:variables
}
