/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.NguoiDungDAO;
import Model.NguoiDung;
import Util.NguoiDungRender;
import Util.SQLConnection;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duc
 */
public class Cu_NguoiDung extends javax.swing.JPanel implements java.beans.Customizer {
    DefaultTableModel dtm = new DefaultTableModel();
    private Object bean;

    /**
     * Creates new customizer Cu_NguoiDung
     */
    public Cu_NguoiDung() {
       initComponents();
        
        loadDuLieuLenLuoi();
        loadComboBox();
        btnXoa.setEnabled(false);
        cbxTrangThai.setSelectedItem(null);
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    public void reset() {

        cbxTrangThai.setSelectedItem(null);
        txtMatKhau.setText("");
        //  txtTenSinhVien.setText("");
        txtTenDangNhap.setText("");
        txtTimKiem.setText("");
        btnThem.setEnabled(true);
        btnXoa.setEnabled(false);
        txtTenDangNhap.setEnabled(true);

    }

    private void loadDuLieuLenLuoi() {
        dtm = new DefaultTableModel();
        //dtm.addColumn("Tên Sinh Viên");

        dtm.addColumn("Tên Đăng Nhập");
        dtm.addColumn("Mật Khẩu");
        dtm.addColumn("Trạng Thái");

        NguoiDungDAO nguoiDungDAO = new NguoiDungDAO();
        List<NguoiDung> nguoiDungList = nguoiDungDAO.selectAll();
        for (NguoiDung nguoiDung : nguoiDungList) {
            Vector vt = new Vector();
            vt.add(nguoiDung.getTenDangNhap());
            vt.add(nguoiDung.getMatKhau());
            vt.add(nguoiDung.getTrangThai());
            dtm.addRow(vt);
        }
        tbl_NguoiDung.setModel(dtm);
    }
    private void loadComboBox() {
        NguoiDungDAO nguoiDungDAO = new NguoiDungDAO();
        List<NguoiDung> nguoiDungList = nguoiDungDAO.selectAll();
        Vector v = new Vector(nguoiDungList);
        DefaultComboBoxModel dcb = new DefaultComboBoxModel(v);
        cbxTrangThai.setModel(dcb);
        cbxTrangThai.setRenderer(new NguoiDungRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtTenDangNhap = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        cbxTrangThai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NguoiDung = new javax.swing.JTable();

        jPanel3.setBackground(new java.awt.Color(214, 0, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 0, 255), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Tên Đăng Nhập");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Mật Khẩu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Trạng Thái");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 0, 255)));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ADD.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        btnReset.setText("Xóa Trắng");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhat)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 0, 255)), "TÌM KIẾM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search-icon.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTimKiem)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTrangThaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtMatKhau)
                    .addComponent(cbxTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thông Tin Người Dùng ", jPanel1);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 0, 255), 2));

        tbl_NguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_NguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NguoiDungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_NguoiDung);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            if (txtTenDangNhap.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Tên Đăng Nhập");
            } else if (txtMatKhau.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Mật Khẩu");
            } else if (cbxTrangThai.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Trạng Thái ");
            }

            NguoiDungDAO nguoiDungD = new NguoiDungDAO();
            NguoiDung nguoiDung = new NguoiDung();
            nguoiDung.setTenDangNhap(txtTenDangNhap.getText());
            nguoiDung.setMatKhau(txtMatKhau.getText());
            nguoiDung.setTrangThai(((NguoiDung) cbxTrangThai.getSelectedItem()).getTrangThai());
            boolean result = nguoiDungD.insert(nguoiDung);
            boolean checkMH = SQLConnection.Kiem_Tra_Trung("tbl_NGUOIDUNG", "TEN_DANG_NHAP", txtTenDangNhap.getText());
            if (result == false) {
                if (checkMH == true) {
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thành Công !");
                } else if (checkMH == false) {
                    JOptionPane.showMessageDialog(this, "Mã Môn Học Đã Tồn Tại, Bạn Vui Lòng Nhập Lại ! ");
                }
            }
            reset();
            loadDuLieuLenLuoi();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xóa Không ", "Thông Báo", OK_CANCEL_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            int row = tbl_NguoiDung.getSelectedRow();
            String tenDangNhap = (String) tbl_NguoiDung.getValueAt(row, 0);
            NguoiDungDAO nguoiDungD = new NguoiDungDAO();
            NguoiDung nguoiDung = new NguoiDung(tenDangNhap);
            boolean result = nguoiDungD.delete(nguoiDung);
            if (result == false) {
                JOptionPane.showMessageDialog(this, "Xóa Thành Công !");
            }
            reset();
            loadDuLieuLenLuoi();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if (txtMatKhau.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Mật Khẩu");
        } else if (cbxTrangThai.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Trạng Thái ");
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Cập Nhật Không ", "Thông Báo", OK_CANCEL_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            NguoiDung nd = new NguoiDung();
            nd.setMatKhau(txtMatKhau.getText());
            nd.setTrangThai(((NguoiDung) cbxTrangThai.getSelectedItem()).getTrangThai());
            nd.setTenDangNhap(txtTenDangNhap.getText());
            NguoiDungDAO lD = new NguoiDungDAO();
            boolean result = lD.update(nd);
            if (result == false) {
                JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công!");
            }
            reset();
            loadDuLieuLenLuoi();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        //        dtm = new DefaultTableModel();
        //        dtm.addColumn("Mã Sinh Viên");
        //        dtm.addColumn("Mã Môn Học");
        //        dtm.addColumn("Điểm Giữa Kỳ");
        //        dtm.addColumn("Điểm Cuối Kỳ");
        //        dtm.addColumn("Điểm Tổng Kết");
        //
        //        NguoiDungDAO nguoiDungDAO = new NguoiDungDAO();
        //
        //
        // NguoiDung d = new NguoiDung(txtMaSinhVien.getText(), txtMaNguoiDung.getText(),  d.setNguoiDungGiuaKy(Float.parseFloat(txtNguoiDungGiuaKy.getText())),d.setNguoiDungCuoiKy(Float.parseFloat(txtNguoiDungCuoiKy.getText())),d.setNguoiDungTongKet(Float.parseFloat(txtNguoiDungTongKet.getText())));

        //     List<NguoiDung> nguoiDungList = nguoiDungDAO.search(d);
        //        for (NguoiDung nguoiDung : nguoiDungList) {
            //            Vector vt = new Vector();
            //            vt.add(nguoiDung.getMaSinhVien());
            //            vt.add(nguoiDung.getMaNguoiDung());
            //            vt.add(nguoiDung.getNguoiDungGiuaKy());
            //            vt.add(nguoiDung.getNguoiDungCuoiKy());
            //            vt.add(nguoiDung.getNguoiDungTongKet());
            //            dtm.addRow(vt);
            //        }
        //        tbl_NguoiDung.setModel(dtm);
        NguoiDungDAO nguoiDungD = new NguoiDungDAO();
        String input = txtTimKiem.getText();
        // nguoiDungD.search1(input);
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String input = txtTimKiem.getText();
        dtm = new DefaultTableModel();

        dtm.addColumn("Tên Đăng Nhập");
        dtm.addColumn("Mật Khẩu");
        dtm.addColumn("Trạng Thái");
        NguoiDungDAO nguoiDungDAO = new NguoiDungDAO();
        List<NguoiDung> diemList = nguoiDungDAO.search(input);
        for (NguoiDung nd : diemList) {
            Vector vt = new Vector();
            vt.add(nd.getTenDangNhap());
            vt.add(nd.getMatKhau());
            vt.add(nd.getTrangThai());

            dtm.addRow(vt);
        }
        tbl_NguoiDung.setModel(dtm);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void cbxTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTrangThaiActionPerformed

    }//GEN-LAST:event_cbxTrangThaiActionPerformed

    private void tbl_NguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NguoiDungMouseClicked
        int row = tbl_NguoiDung.getSelectedRow();
        String tenDangNhap = (String) tbl_NguoiDung.getValueAt(row, 0);
        String matKhau = (String) tbl_NguoiDung.getValueAt(row, 1);
        String trangThai = (String) tbl_NguoiDung.getValueAt(row, 2);

        txtTenDangNhap.setText(tenDangNhap);
        txtMatKhau.setText(matKhau);
        NguoiDungDAO ngd = new NguoiDungDAO();
        cbxTrangThai.setSelectedItem(ngd.getTrangThaiID(trangThai));
        btnThem.setEnabled(false);
        btnXoa.setEnabled(true);
        txtTenDangNhap.setEnabled(false);
    }//GEN-LAST:event_tbl_NguoiDungMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_NguoiDung;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
