/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LopDAO;
import Controller.SinhVienDAO;
import Model.Lop;
import Model.SinhVien;
import Util.MaLopRender;
import Util.SQLConnection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duc
 */
public class Cu_SinhVien extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
 DefaultTableModel dtm = new DefaultTableModel();
    private HashMap<String, String> map = new HashMap<String, String>();
    /**
     * Creates new customizer Cu_SinhVien
     */
    public Cu_SinhVien() {
      initComponents();
       
        loadDuLieuLenLuoi();
        loadComboBox();
        btnXoa.setEnabled(false);
        btnCapNhat.setEnabled(false);
        cbxMaLop.setSelectedItem(null);
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
     public void reset() {
        txtMaSinhVien.setText("");
        txtTenSinhVien.setText("");
        rbtNam.setSelected(false);
        rbtNu.setSelected(false);
        dtcNgaySinh.setDate(null);
        txtQueQuan.setText("");
        txtSoDienThoai.setText("");
        txtEmail.setText("");
        // txtMaLop.setText("");
        cbxMaLop.setSelectedItem(null);
        txtTimKiem.setText("");
        btnThem.setEnabled(true);
        btnXoa.setEnabled(false);
        btnCapNhat.setEnabled(false);
        txtMaSinhVien.setEnabled(true);

    }

    private void loadDuLieuLenLuoi() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        dtm = new DefaultTableModel();
        //dtm.addColumn("Tên Sinh Viên");

        dtm.addColumn("Mã Sinh Viên");
        dtm.addColumn("Tên Sinh Viên");
        dtm.addColumn("Giới Tính");
        dtm.addColumn("Ngày Sinh");
        dtm.addColumn("Quê Quán");
        dtm.addColumn("Số Điện Thoại");
        dtm.addColumn("Email");
        dtm.addColumn("Mã Lớp");

        SinhVienDAO sinhVienDAO = new SinhVienDAO();
        List<SinhVien> sinhVienList = sinhVienDAO.selectAll();
        for (SinhVien sinhVien : sinhVienList) {
            Vector vt = new Vector();
            vt.add(sinhVien.getMaSinhVien());
            vt.add(sinhVien.getTenSinhVien());
            vt.add(sinhVien.getGioiTinh() ? "Nam" : "Nữ");
            vt.add(sinhVien.getNgaySinh() != null ? sdf.format(sinhVien.getNgaySinh()) : "");
            vt.add(sinhVien.getQueQuan());
            vt.add(sinhVien.getSDT());
            vt.add(sinhVien.getEmail());
            vt.add(sinhVien.getMaLop());
            dtm.addRow(vt);
        }
        tbl_SinhVien.setModel(dtm);
    }
    private void loadComboBox() {
        LopDAO lopDAO = new LopDAO();
        List<Lop> lopList = lopDAO.selectAll();
        Vector v = new Vector(lopList);
        DefaultComboBoxModel dcb = new DefaultComboBoxModel(v);
        cbxMaLop.setModel(dcb);
        cbxMaLop.setRenderer(new MaLopRender());

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtMaSinhVien = new javax.swing.JTextField();
        txtTenSinhVien = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbtNam = new javax.swing.JRadioButton();
        rbtNu = new javax.swing.JRadioButton();
        dtcNgaySinh = new com.toedter.calendar.JDateChooser();
        txtEmail = new javax.swing.JTextField();
        cbxMaLop = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SinhVien = new javax.swing.JTable();

        jPanel3.setBackground(new java.awt.Color(12, 201, 232));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 201, 232), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Mã Sinh Viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Tên Sinh Viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Giới Tính");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Ngày Sinh");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Quê Quán");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 201, 232)));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon("C:\\Users\\msi\\Documents\\NetBeansProjects\\QLDIEMMM\\src\\icon\\ADD.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\msi\\Documents\\NetBeansProjects\\QLDIEMMM\\src\\icon\\delete.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon("C:\\Users\\msi\\Documents\\NetBeansProjects\\QLDIEMMM\\src\\icon\\edit.png")); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\msi\\Documents\\NetBeansProjects\\QLDIEMMM\\src\\icon\\update.png")); // NOI18N
        btnReset.setText("Xóa Trắng");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhat)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 201, 232)), "TÌM KIẾM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search-icon.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addComponent(btnTimKiem)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("SĐT");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Mã Lớp");

        rbtNam.setText("Nam");

        rbtNu.setText("Nữ");

        cbxMaLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxMaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(rbtNam)
                                .addGap(18, 18, 18)
                                .addComponent(rbtNu))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dtcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtQueQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(cbxMaLop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtNam)
                    .addComponent(rbtNu)
                    .addComponent(jLabel7)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbxMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông Tin Sinh Viên", jPanel1);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 201, 232), 2));

        tbl_SinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_SinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_SinhVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {//chưa báo lỗi date và mã lớp chưa được chọn
            if (txtMaSinhVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Mã Sinh Viên");
            } else if (txtTenSinhVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Tên Sinh Viên");
            } else if (!rbtNam.isSelected() && !rbtNu.isSelected()) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Giới Tính");
            } else if (txtQueQuan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Quê Quán");
            } else if (txtSoDienThoai.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Số Điện Thoại");
            } else if (txtEmail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Email");
            } else if (cbxMaLop.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Mã Lớp");
            }

            SinhVienDAO sinhVienD = new SinhVienDAO();
            SinhVien sv = new SinhVien();
            sv.setMaSinhVien(txtMaSinhVien.getText());
            sv.setTenSinhVien(txtTenSinhVien.getText());
            boolean gioiTinh = false;
            if (rbtNam.isSelected()) {
                gioiTinh = true;
            }
            if (rbtNu.isSelected()) {
                gioiTinh = true;
            }
            sv.setGioiTinh(gioiTinh);
            sv.setNgaySinh(dtcNgaySinh.getDate());
            sv.setQueQuan(txtQueQuan.getText());
            sv.setSDT(txtSoDienThoai.getText());
            sv.setEmail(txtEmail.getText());
            sv.setMaSinhVien(txtMaSinhVien.getText());
            sv.setMaLop(((Lop) cbxMaLop.getSelectedItem()).getMaLop());
            boolean result = sinhVienD.insert(sv);
            boolean checkMH = SQLConnection.Kiem_Tra_Trung("tbl_MONHOC", "MA_MON_HOC", txtMaSinhVien.getText());
            if (result == false) {
                if (checkMH == false) {
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thành Công !");
                } else if (checkMH == true) {
                    JOptionPane.showMessageDialog(this, "Mã Môn Học Đã Tồn Tại, Bạn Vui Lòng Nhập Lại ! ");
                }
            }

            reset();
            loadDuLieuLenLuoi();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xóa Không ", "Thông Báo", OK_CANCEL_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            int row = tbl_SinhVien.getSelectedRow();
            String maSinhVien = (String) tbl_SinhVien.getValueAt(row, 0);
            SinhVienDAO sinhVienD = new SinhVienDAO();
            SinhVien sinhVien = new SinhVien(maSinhVien);
            boolean result = sinhVienD.delete(sinhVien);
            if (result == false) {
                JOptionPane.showMessageDialog(this, "Xóa Thành Công !");
            }
            reset();
            loadDuLieuLenLuoi();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if (txtTenSinhVien.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Tên Sinh Viên");
        } else if (!rbtNam.isSelected() && !rbtNu.isSelected()) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Giới Tính");
        } else if (txtQueQuan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Quê Quán");
        } else if (txtSoDienThoai.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Số Điện Thoại");
        } else if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Email");
        } else if (cbxMaLop.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Mã Lớp");
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Cập Nhật Không ", "Thông Báo", OK_CANCEL_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            //SinhVien mh = new SinhVien(txtTenSinhVien.getText(), Integer.parseInt(txtSoDienThoai.getText()), Float.parseFloat(txtHeSo_GiuaKy.getText()), Float.parseFloat(txtQueQuan.getText()));
            SinhVien sv = new SinhVien();
            sv.setTenSinhVien(txtTenSinhVien.getText());
            boolean gioiTinh = false;
            if (rbtNam.isSelected()) {
                gioiTinh = true;
            }
            if (rbtNu.isSelected()) {
                gioiTinh = true;
            }
            sv.setGioiTinh(gioiTinh);
            sv.setNgaySinh(dtcNgaySinh.getDate());
            sv.setQueQuan(txtQueQuan.getText());
            sv.setSDT(txtSoDienThoai.getText());
            sv.setEmail(txtEmail.getText());
            sv.setMaLop(((Lop) cbxMaLop.getSelectedItem()).getMaLop());
            sv.setMaSinhVien(txtMaSinhVien.getText());
            SinhVienDAO mhD = new SinhVienDAO();
            boolean result = mhD.update(sv);
            if (result == false) {
                JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công!");
            }
            reset();
            loadDuLieuLenLuoi();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        //        dtm = new DefaultTableModel();
        //        dtm.addColumn("Mã Sinh Viên");
        //        dtm.addColumn("Mã Môn Học");
        //        dtm.addColumn("Điểm Giữa Kỳ");
        //        dtm.addColumn("Điểm Cuối Kỳ");
        //        dtm.addColumn("Điểm Tổng Kết");
        //
        //        SinhVienDAO sinhVienDAO = new SinhVienDAO();
        //
        //
        // SinhVien d = new SinhVien(txtMaSinhVien.getText(), txtMaSinhVien.getText(),  d.setSinhVienGiuaKy(Float.parseFloat(txtSinhVienGiuaKy.getText())),d.setSinhVienCuoiKy(Float.parseFloat(txtSinhVienCuoiKy.getText())),d.setSinhVienTongKet(Float.parseFloat(txtSinhVienTongKet.getText())));

        //     List<SinhVien> sinhVienList = sinhVienDAO.search(d);
        //        for (SinhVien sinhVien : sinhVienList) {
            //            Vector vt = new Vector();
            //            vt.add(sinhVien.getMaSinhVien());
            //            vt.add(sinhVien.getMaSinhVien());
            //            vt.add(sinhVien.getSinhVienGiuaKy());
            //            vt.add(sinhVien.getSinhVienCuoiKy());
            //            vt.add(sinhVien.getSinhVienTongKet());
            //            dtm.addRow(vt);
            //        }
        //        tbl_SinhVien.setModel(dtm);
        SinhVienDAO sinhVienD = new SinhVienDAO();
        String input = txtTimKiem.getText();
        // sinhVienD.search1(input);
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String input = txtTimKiem.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        dtm = new DefaultTableModel();

        dtm.addColumn("Mã Sinh Viên");
        dtm.addColumn("Tên Sinh Viên");
        dtm.addColumn("Giới Tính");
        dtm.addColumn("Ngày Sinh");
        dtm.addColumn("Quê Quán");
        dtm.addColumn("Số Điện Thoại");
        dtm.addColumn("Email");
        dtm.addColumn("Mã Lớp");
        SinhVienDAO sinhVienDAO = new SinhVienDAO();
        List<SinhVien> sinhVienList = sinhVienDAO.search(input);
        for (SinhVien sv : sinhVienList) {
            Vector vt = new Vector();
            vt.add(sv.getMaSinhVien());
            vt.add(sv.getTenSinhVien());
            vt.add(sv.getGioiTinh() ? "Nam" : "Nữ");
            vt.add(sv.getNgaySinh() != null ? sdf.format(sv.getNgaySinh()) : "");
            vt.add(sv.getQueQuan());
            vt.add(sv.getSDT());
            vt.add(sv.getEmail());
            vt.add(sv.getMaLop());
            dtm.addRow(vt);
        }
        tbl_SinhVien.setModel(dtm);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void cbxMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaLopActionPerformed
        //        JComboBox<String> source = ((JComboBox<String>) evt.getSource());
        //        String maLop = source.getItemAt(source.getSelectedIndex());
        //        String var_Ma_Lop = map.get(maLop);
        //((VaiTro) cbbNhanVien.getSelectedItem()).getQuyen()
    }//GEN-LAST:event_cbxMaLopActionPerformed

    private void tbl_SinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SinhVienMouseClicked
        try {
            int row = tbl_SinhVien.getSelectedRow();
            String maSinhVien = (String) tbl_SinhVien.getValueAt(row, 0);
            String tenSinhVien = (String) tbl_SinhVien.getValueAt(row, 1);
            String gioiTinh = (String) tbl_SinhVien.getValueAt(row, 2);
            String ngaySinh = (String) tbl_SinhVien.getValueAt(row, 3);
            String queQuan = (String) tbl_SinhVien.getValueAt(row, 4);
            String sDT = (String) tbl_SinhVien.getValueAt(row, 5);
            String email = (String) tbl_SinhVien.getValueAt(row, 6);
            String maLop = (String) tbl_SinhVien.getValueAt(row, 7);

            txtMaSinhVien.setText(maSinhVien);
            txtTenSinhVien.setText(tenSinhVien);
            if (gioiTinh.equalsIgnoreCase("Nam")) {
                rbtNam.setSelected(true);
            } else {
                rbtNu.setSelected(true);
            }
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            dtcNgaySinh.setDate(ngaySinh != null && ngaySinh != "" ? sdf.parse(ngaySinh) : null);
            txtQueQuan.setText(queQuan);
            txtSoDienThoai.setText(sDT);
            txtEmail.setText(email);
            // txtMaLop.setText(maLop);
            btnCapNhat.setEnabled(true);
            btnThem.setEnabled(false);
            btnXoa.setEnabled(true);
            txtMaSinhVien.setEnabled(false);
            //cbbVaiTro.setSelectedItem(vaiTroDAO.getVaiTroById(maVaiTro));
            LopDAO lopDAO = new LopDAO();
            cbxMaLop.setSelectedItem(lopDAO.getMaLopID(maLop));
            // txtMaLop.setEnabled(false);
        } catch (ParseException ex) {
            Logger.getLogger(FrmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbl_SinhVienMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxMaLop;
    private com.toedter.calendar.JDateChooser dtcNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbtNam;
    private javax.swing.JRadioButton rbtNu;
    private javax.swing.JTable tbl_SinhVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenSinhVien;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
