/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Duc
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
         setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        container = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        lop = new javax.swing.JMenuItem();
        monhoc = new javax.swing.JMenuItem();
        sinhvien = new javax.swing.JMenuItem();
        nguoidung = new javax.swing.JMenuItem();
        diem = new javax.swing.JMenuItem();

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 1, 0)));
        container.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bachkhoa3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(8, 93, 152));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chào Mừng Đến Với Phần Mềm Quản Lý Điểm Sinh Viên ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        container.addTab("HOME", home);

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 153));
        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(152, 1, 0), 2, true));
        jMenuBar1.setForeground(new java.awt.Color(204, 0, 0));

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-system-run-icon.png"))); // NOI18N
        jMenu1.setText("Hệ Thống        ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout-icon.png"))); // NOI18N
        jMenuItem1.setText("Đăng Xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Apps-file-manager-icon.png"))); // NOI18N
        jMenu2.setText("Danh Mục Quản Lý");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lop.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Science-Classroom-icon.png"))); // NOI18N
        lop.setText("Quản Lý Lớp");
        lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopActionPerformed(evt);
            }
        });
        jMenu2.add(lop);

        monhoc.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        monhoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Categories-applications-education-school-icon.png"))); // NOI18N
        monhoc.setText("Quản Lý Môn Học");
        monhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monhocActionPerformed(evt);
            }
        });
        jMenu2.add(monhoc);

        sinhvien.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        sinhvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Distributor-report-icon.png"))); // NOI18N
        sinhvien.setText("Quản Lý Sinh Viên");
        sinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinhvienActionPerformed(evt);
            }
        });
        jMenu2.add(sinhvien);

        nguoidung.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        nguoidung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Folder-Blank-sample-icon.png"))); // NOI18N
        nguoidung.setText("Quản Lý Người Dùng");
        nguoidung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nguoidungActionPerformed(evt);
            }
        });
        jMenu2.add(nguoidung);

        diem.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        diem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Rich-Text-Editor-icon.png"))); // NOI18N
        diem.setText("Quản Lý Điểm");
        diem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemActionPerformed(evt);
            }
        });
        jMenu2.add(diem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void lopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopActionPerformed
        Cu_Lop lop = new Cu_Lop();
        container.removeAll();
        container.add("Bảng Lớp" , lop);
    }//GEN-LAST:event_lopActionPerformed

    private void diemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemActionPerformed
       Cu_Diem diem = new Cu_Diem();
       container.removeAll();
      
       container.add("Bảng Điểm",diem);
    }//GEN-LAST:event_diemActionPerformed

    private void monhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monhocActionPerformed
        Cu_MonHoc mh = new Cu_MonHoc();
        container.removeAll();
        container.add("Bảng Môn Học" , mh);
    }//GEN-LAST:event_monhocActionPerformed

    private void sinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinhvienActionPerformed
        Cu_SinhVien sv = new Cu_SinhVien();
        container.removeAll();
        container.add("Bảng Sinh Viên",sv);
    }//GEN-LAST:event_sinhvienActionPerformed

    private void nguoidungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nguoidungActionPerformed
        Cu_NguoiDung nd = new Cu_NguoiDung();
        container.removeAll();
        container.add("Bảng Người Dùng",nd);
    }//GEN-LAST:event_nguoidungActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmDangNhap dn = new FrmDangNhap();
        dn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane container;
    private javax.swing.JMenuItem diem;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem lop;
    private javax.swing.JMenuItem monhoc;
    private javax.swing.JMenuItem nguoidung;
    private javax.swing.JMenuItem sinhvien;
    // End of variables declaration//GEN-END:variables
}
